// Master list of all major Indian & Regional Cities (Telangana, Andhra Pradesh, and National Hubs)
export const ALL_INDIAN_CITIES = [
  // Top Metros & State Capitals
  'Hyderabad',
  'Vijayawada',
  'Visakhapatnam',
  'Bengaluru',
  'Chennai',
  'Mumbai',
  'Delhi NCR',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  'Kochi',
  'Coimbatore',

  // Telangana Cities & Districts
  'Secunderabad',
  'Warangal',
  'Karimnagar',
  'Nizamabad',
  'Khammam',
  'Ramagundam',
  'Mahabubnagar',
  'Nalgonda',
  'Adilabad',
  'Suryapet',
  'Siddipet',
  'Mancherial',
  'Jagtial',
  'Kamareddy',
  'Kothagudem',
  'Miryalaguda',
  'Bhadradri',
  'Sangareddy',
  'Medak',
  'Wanaparthy',
  'Gadwal',
  'Nirmal',
  'Vikarabad',

  // Andhra Pradesh Cities & Districts
  'Amaravati',
  'Guntur',
  'Tirupati',
  'Nellore',
  'Kurnool',
  'Kakinada',
  'Rajahmundry',
  'Kadapa',
  'Anantapur',
  'Vizianagaram',
  'Eluru',
  'Ongole',
  'Nandyal',
  'Machilipatnam',
  'Tenali',
  'Proddatur',
  'Chittoor',
  'Hindupur',
  'Bhimavaram',
  'Madanapalle',
  'Guntakal',
  'Dharmavaram',
  'Gudivada',
  'Srikakulam',
  'Narasaraopet',
  'Tadipatri',
  'Tadepalligudem',
  'Chilakaluripet',
  'Yemmiganur',
  'Kadiri',
  'Rayachoti',
  'Tanuku',
  'Amalapuram',
  'Bapatla',
  'Markapur',
  'Mangalagiri',
  'Palakollu',
  'Puttaparthi',
  'Sattenapalle',
  'Kavali',
  'Gudur',
  'Narsapur',

  // Karnataka
  'Mysuru',
  'Mangalore',
  'Hubballi-Dharwad',
  'Belagavi',
  'Kalaburagi',
  'Ballari',
  'Davangere',
  'Shimoga',
  'Tumakuru',
  'Udupi',

  // Tamil Nadu & Kerala
  'Madurai',
  'Tiruchirappalli',
  'Salem',
  'Tirunelveli',
  'Erode',
  'Vellore',
  'Thiruvananthapuram',
  'Kozhikode',
  'Thrissur',
  'Kollam',
  'Kannur',

  // Maharashtra & Western India
  'Nagpur',
  'Nashik',
  'Thane',
  'Navi Mumbai',
  'Aurangabad',
  'Solapur',
  'Kolhapur',
  'Surat',
  'Vadodara',
  'Rajkot',
  'Panaji (Goa)',

  // North & East India
  'Jaipur',
  'Lucknow',
  'Kanpur',
  'Varanasi',
  'Agra',
  'Prayagraj',
  'Noida',
  'Gurugram',
  'Chandigarh',
  'Indore',
  'Bhopal',
  'Patna',
  'Bhubaneswar',
  'Cuttack',
  'Raipur',
  'Ranchi',
  'Jamshedpur',
  'Guwahati'
];

export const getCombinedCities = (hospitals = []) => {
  const registeredCities = hospitals.map(h => h.city?.trim()).filter(Boolean);
  return Array.from(new Set([...ALL_INDIAN_CITIES, ...registeredCities])).sort((a, b) => a.localeCompare(b));
};
